### Get all balances
GET http://localhost:3001/balances



### Add a new user
POST http://localhost:3001/balances/add
X-User-ID: 12345
Content-Type: application/json


### update a new balance
PUT http://localhost:3001/balances/update
X-User-ID: 12345
Content-Type: application/json

{
  "coin": "bitcloin",
  "amount": 0.5
}

### Get ethereum price in ILS
GET http://localhost:3002/rates/price?coin=ethereum&currency=ils
### Get ethereum price in ILS
GET http://localhost:3002/rates/price?coin=ethereum&currency=ils&skipCache=true

### Get ethereum price in USD
GET http://localhost:3002/rates/price?coin=ethereum&currency=usd

### Get supported coins
GET http://localhost:3002/rates/coins

### Get supported currencies
GET http://localhost:3002/rates/currencies