// balance service requests

### Get all balances
GET http://localhost:3001/balances

### Add a new user
POST http://localhost:3001/balances/user/add
X-User-ID: 1234567
Content-Type: application/json

### delete user
DELETE http://localhost:3001/balances/user/remove
X-User-ID: 1234545
Content-Type: application/json


### update a new balance
PUT http://localhost:3001/balances/user/update
X-User-ID: 1234567
Content-Type: application/json

{
  "coin": "bitcoin", 
  "amount": 0.5
}

### rebalance
PUT http://localhost:3001/balances/user/rebalance
X-User-ID: 123456
Content-Type: application/json

{
  "bitcoin": 50, "ethereum": 30, "1move token": 20
}

### Get User Balance Value
GET http://localhost:3001/balances/user/value?currency=ils
x-user-id: 1234567



//rate service requests

### Get bitcoin price in USD
GET http://localhost:3002/rates/rate?coin=bitcoin&currency=usd

### Get ethereum price in USD
GET http://localhost:3002/rates/rate?coin=ethereum&currency=usd

### Get ethereum price in ILS
GET http://localhost:3002/rates/rate?coin=ethereum&currency=ils&skipCache=true

### coin not exist
GET http://localhost:3002/rates/rate?coin=ethdsadaeum&currency=ils&skipCache=true

### currency not exist
GET http://localhost:3002/rates/rate?coin=ethereum&currency=issss&skipCache=true


### Get supported coins
GET http://localhost:3002/rates/coins

### Get supported currencies
GET http://localhost:3002/rates/currencies

### Get multiple coin rates
GET http://localhost:3002/rates?coins=ethereum,bitcoin&currency=ils
Content-Type: application/json
